version: '3.8'
services:

  embeddings:
    build:
      context: ./embeddings_iep

    container_name: embeddings_iep
    networks:
      - my_network
    ports:
      - "5001:5001"

  gpt:
    build:
      context: ./gpt_iep

    container_name: gpt_iep
    networks:
      - my_network
    ports:
      - "5002:5002"

  eep:
    build:
      context: ./eep

    container_name: eep
    networks:
      - my_network
    ports:
      - "5000:5000"
  

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
