version: '3.8'
services:

  inventory:
    build:
      context: ./embeddings_iep

    container_name: embeddings_iep
    networks:
      - my_network
    ports:
      - "3001:3001"

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
