version: '3.8'
services:

  embeddings:
    build:
      context: ./embeddings_iep

    container_name: embeddings_iep
    networks:
      - my_network
    ports:
      - "5001:5001"

  gpt:
    build:
      context: ./gpt_iep

    container_name: gpt_iep
    networks:
      - my_network
    ports:
      - "5002:5002"

  audio_gen:
    build:
      context: ./audio_gen_iep

    container_name: audio_gen_iep
    networks:
      - my_network
    ports:
      - "5003:5003"

  eep:
    build:
      context: ./eep

    container_name: eep
    networks:
      - my_network
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090" 
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000" 
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'  
    restart: always
    depends_on:
      - prometheus

  

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
