apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: audio-gen-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audio-gen
  minReplicas: 0
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
