apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "~^https://(white-forest-06d13af00\.6\.azurestaticapps\.net|learnify503n\.space)$"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - learnify503n.space
      secretName: learnify-tls
  rules:
    - host: learnify503n.space
      http:
        paths:
          - path: /api/eep(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: eep
                port:
                  number: 5000
          - path: /api/gpt(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: gpt
                port:
                  number: 5002
          - path: /api/audio-gen(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: audio-gen
                port:
                  number: 5003
          - path: /api/embeddings(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: embeddings
                port:
                  number: 5001
          - path: /api/course-creator(/|$)(.*)    
            pathType: Prefix
            backend:
              service:
                name: course-creator              
                port:
                  number: 5004
          - path: /()(.*)  # frontend fallback
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /prometheus(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
