apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # Scrape every 15 seconds

    scrape_configs:
      - job_name: 'flask_app'
        static_configs:
          - targets: ['host.docker.internal:8000']  # Use 'host.docker.internal' to access local machine from Docker
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
