name: Build and Deploy to AKS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: ACR Login
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and push app1
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/app1:latest ./app1
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/app1:latest

    - name: Build and push app2
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/app2:latest ./app2
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/app2:latest

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/
