name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login using federated token
      run: |
        echo "Getting ID token from GitHub OIDC provider..."
        AZ_TOKEN=$(curl -sLSH "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')
    
        echo "Logging in to Azure CLI using federated token..."
        az login --service-principal \
          --federated-token "$AZ_TOKEN" \
          --tenant ${{ secrets.AZURE_TENANT_ID }} \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --allow-no-subscriptions
      shell: bash
      
    - name: Login to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and push app images
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/audio-gen:latest ./audio_gen_iep
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/audio-gen:latest

        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/eep:latest ./eep
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/eep:latest

        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/embeddings:latest ./embeddings_iep
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/embeddings:latest

        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest ./frontend
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/gpt:latest ./gpt_iep
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/gpt:latest

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER }}

    - name: Inject secrets into Kubernetes Secret
      run: |
        kubectl create secret generic app-secrets \
          --from-literal=api-key="${{ secrets.OPENAI_API_KEY }}" \
          --from-literal=db-password="${{ secrets.DB_PASSWORD }}" \
          --from-literal=ca-cert="${{ secrets.DigiCert_CA_Cert }}" \
          --from-literal=secret-key="${{ secrets.SECRET_KEY }}" \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/env-configmap.yaml
        kubectl apply -f k8s/audio-gen-deployment.yaml
        kubectl apply -f k8s/audio_gen-service.yaml
        kubectl apply -f k8s/eep-deployment.yaml
        kubectl apply -f k8s/eep-service.yaml
        kubectl apply -f k8s/embeddings-deployment.yaml
        kubectl apply -f k8s/embeddings-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
        kubectl apply -f k8s/gpt-deployment.yaml
        kubectl apply -f k8s/gpt-service.yaml
